---
- name: restart nginx
  service:
    name: nginx
    state: restarted
  register: nginx_restart

- name: Проверка статуса Nginx
  shell: systemctl status nginx | grep Active
  register: nginx_status
  changed_when: false
  listen: restart nginx
